[sncast.default]
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"
account = "sepolia"
accounts-file = "~/.starknet_foundry_accounts"
block-explorer = "StarkScan"
show-explorer-links = true
wait-params = { timeout = 300, retry-interval = 10 }
